### ISSUE TITLE
Have you considered GitHub pages?

### ISSUE THREAD

**Issue by lmammino** [tobilg/lambda-runtimes#1]
Very interesting project 👏🏽 

I just wanted to ask if you have considered GitHub pages as an alternative to CloudFront.

The 2 main advantages I see:

- You can pick your (more idiomatic URL). If you use this repo it would be something like: `https://tobilg.github.io/lambda-runtimes/`
- Cost (basically free!)

If you need an example, I have done this for an API returning tech quotes: https://github.com/FullStackBulletin/tech-quotes

**Comment by tobilg** [comment]
Hi @lmammino, thanks for this suggestion! As far as I understood, you're also writing static files, which you then host via GH Pages? If so, will GH Pages automatically set the right Content-Type headers etc. as well?

**Comment by lmammino** [comment]
> Hi @lmammino, thanks for this suggestion! As far as I understood, you're also writing static files, which you then host via GH Pages? If so, will GH Pages automatically set the right Content-Type headers etc. as well?

Yes, it does :) it's a fully-fledged CDN

<img width="873" alt="Screenshot 2023-10-22 at 17 55 26" src="https://github.com/tobilg/lambda-runtimes/assets/205629/1308afb6-c22d-4599-a336-34593b1375a1">

**Comment by tobilg** [comment]
Nice, thanks, will have a look. I could probably also just assign a domain to the CloudFront distribution, but I don't really have a matching one at the moment, and didn't want to spent som extra money for a new domain.

**Comment by tobilg** [comment]
Site has been migrated to GitHub Pages. Thanks again @lmammino
